server:
  port: 8890


#eureka:
#  instance:
#    instance-id: WorkWeChatApplicaiton_8890
#  client:
#    service-url:
#      defaultZone:  http://localhost:7001/eureka,http://localhost:7002/eureka

spring:
  application:
    name: WorkWeChat
