server:
  port: 8789

spring:
  application:
    name: ZuulApplication-8789

eureka:
  instance:
    instance-id: ZuulApplication-8789
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/


zuul:
  prefix: /zrb
  routes:
    user-service:
      serviceId: spring-provider-8001
      path: /test/**
  ignored-services:
    - spring-provider-8001


#设置routes接口可访问，该接口可以查看所以允许转发的请求
management:
  endpoints:
    web:
      exposure:
        include:
          - routes