server:
  port : 7002

#Eureka 配置
eureka:
  instance:
    # Eureka 服务端实例名称
    hostname: localhost_7002
  client:
    # 表示 是否向Eureka 注册中心注册自己
    register-with-eureka: false
    # 如果为false表示自己为主机（注册中心）
    fetch-registry: false
    #服务地址 监控页面
    service-url:
      #单机
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群
      defaultZone: http://localhost:7001/eureka/
